/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import testSuite.AutoCreatedSuite;
	import testSuite.SampleSuite;
	import testSuite.tests.FileServiceTests;
	import testSuite.tests.MeshGroupFactoryTests;
	import testSuite.tests.SceneProxyTests;
	import testSuite.tests.SocketServiceTests;
	import testSuite.tests.TestAsync;
	import testSuite.tests.TestAsyncSetup;
	import testSuite.tests.TestCase1;
	import testSuite.tests.TestSequences;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var testSuite_tests_TestSequences_obj:testSuite.tests.TestSequences;
		private var testSuite_tests_SceneProxyTests_obj:testSuite.tests.SceneProxyTests;
		private var testSuite_tests_TestAsync_obj:testSuite.tests.TestAsync;
		private var testSuite_tests_TestAsyncSetup_obj:testSuite.tests.TestAsyncSetup;
		private var testSuite_tests_SocketServiceTests_obj:testSuite.tests.SocketServiceTests;
		private var testSuite_tests_MeshGroupFactoryTests_obj:testSuite.tests.MeshGroupFactoryTests;
		private var testSuite_tests_FileServiceTests_obj:testSuite.tests.FileServiceTests;
		private var testSuite_tests_TestCase1_obj:testSuite.tests.TestCase1;
		private var testSuite_AutoCreatedSuite_obj:testSuite.AutoCreatedSuite;
		private var testSuite_SampleSuite_obj:testSuite.SampleSuite;
	}
}