/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import org.floxy.ProxyRepositoryTest;
	import org.floxy.event.ProxyClassEventTest;
	
	import testSuite.AutoCreatedSuite;
	import testSuite.SampleSuite;
	import testSuite.tests.FileServiceTests;
	import testSuite.tests.MeshGroupFactoryTests;
	import testSuite.tests.SceneProxyTests;
	import testSuite.tests.SocketServiceTests;
	import testSuite.tests.TestAsyncBoilerplate;
	import testSuite.tests.TestAsyncSetupBoilerplate;
	import testSuite.tests.TestCaseBoilerplate;
	import testSuite.tests.TestSequencesBoilerplate;
	import testSuite.tests.view.CreatePrimitiveMediatorTests;
	import testSuite.tests.view.MeshGroupContainer3DTests;
	import testSuite.tests.view.Canvas3DmediatorTests;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var testSuite_tests_view_Canvas3DmediatorTests_obj:testSuite.tests.view.Canvas3DmediatorTests;
		
		private var testSuite_tests_SocketServiceTests_obj:testSuite.tests.SocketServiceTests;
		private var testSuite_tests_TestAsync_obj:testSuite.tests.TestAsyncBoilerplate;
		private var testSuite_tests_view_CreatePrimitiveMediatorTests_obj:testSuite.tests.view.CreatePrimitiveMediatorTests;
		private var testSuite_tests_TestAsyncSetup_obj:testSuite.tests.TestAsyncSetupBoilerplate;
		private var testSuite_tests_view_MeshGroupContainer3DTests_obj:testSuite.tests.view.MeshGroupContainer3DTests;
		private var org_floxy_event_ProxyClassEventTest_obj:org.floxy.event.ProxyClassEventTest;
		private var testSuite_tests_TestSequences_obj:testSuite.tests.TestSequencesBoilerplate;
		private var testSuite_tests_MeshGroupFactoryTests_obj:testSuite.tests.MeshGroupFactoryTests;
		private var testSuite_tests_SceneProxyTests_obj:testSuite.tests.SceneProxyTests;
		private var testSuite_tests_TestCase1_obj:testSuite.tests.TestCaseBoilerplate;
		private var testSuite_tests_FileServiceTests_obj:testSuite.tests.FileServiceTests;
		private var org_floxy_ProxyRepositoryTest_obj:org.floxy.ProxyRepositoryTest;
		private var testSuite_AutoCreatedSuite_obj:testSuite.AutoCreatedSuite;
		private var testSuite_SampleSuite_obj:testSuite.SampleSuite;
	}
}